version: '3.3'
networks:
  laravel:
services:
  site:
    image: nginx:stable-alpine
    build:
        context: .
        dockerfile: nginx.dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/medical
    depends_on:
      - php
      - mysql
    networks:
      - laravel
  mysql:
    image: mysql:5.7
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: php.dockerfile
    volumes:
      - ./:/var/www/medical
    ports:
      - "9000:9000"
    networks:
      - laravel
  composer:
    image: composer:latest
    volumes:
      - ./:/var/www/medical
    working_dir: /var/www/medical
    depends_on:
      - php
    networks:
      - laravel

  artisan:
    build:
      context: .
      dockerfile: php.dockerfile
    volumes:
      - ./:/var/www/medical
    depends_on:
      - mysql
    working_dir: /var/www/html
    entrypoint: ['php', '/var/www/medical/artisan']
    networks:
      - laravel
